### ISSUE TITLE
3.3 Ajax有个疑问

### ISSUE THREAD

**Issue by shin-ruby** [liwei78/rails-practice#1]
Hey 里克
感谢你写的Rails Practice，在3.3小节我学到了不少Ajax知识点；
3.3小节我有个问题，在New一个新的产品成功后，我继续New一个新产品，但在弹出的modal表单里会有上一个已保存的产品数据；我想这时弹出的modal表单里是空的无任何数据，这点因该如何处理？谢谢！

**Comment by liwei78** [comment]
hi，感谢你的留言。
在 shop3.3这个项目里，`app/views/products/create.js.erb`里使用了一个方法：

```
$('#newProductForm')[0].reset();
```

希望能有帮助。

**Comment by liwei78** [comment]
@shin-ruby  我说的代码在这里 https://github.com/liwei78/rails-practice-code/tree/master/chapter_3/shop3.3

这里有每个章节对应的代码

**Comment by shin-ruby** [comment]
哇！太感谢了，我是从3.1一步步做到3.3，这段代码遗漏了 ：） 感谢回复！
继续期待后续的章节！

**Comment by liwei78** [comment]
客气啦。
