### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by xi4oh4o** [liwei78/rails-practice#12]
### config 文件夹
- envirments  -> environment

**Comment by liwei78** [comment]
fixed, thank you.

**Comment by xi4oh4o** [comment]
@liwei78 
http://rails-practice.com/content/Chapter_2/2.3.html
- http://localhost:3000/home/aaa/index -> http://localhost:3000/something/home/aaa/index

**Comment by liwei78** [comment]
fixed，非常非常感谢。

**Comment by xi4oh4o** [comment]
@liwei78 
http://rails-practice.com/content/Chapter_2/2.3.html
- resources :vriants -> resources :variants

**Comment by liwei78** [comment]
@xi4oh4o fixed :smile:

**Comment by xi4oh4o** [comment]
@liwei78 thank for you :+1:
