### ISSUE TITLE
请教bundle 的问题

### ISSUE THREAD

**Issue by jfcai** [liwei78/rails-practice#13]
老师你好！我刚开始学习Ruby,按照您的教程做一下，一开始就被难住了。问题出在使用Bootstrap后提示错误，详细错误好下：

> Completed 500 Internal Server Error in 328ms
> ActionView::Template::Error (undefined method `[]' for nil:NilClass):
>     12:       <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
>     13:     <![endif]-->
>     14: 
>     15:     <%= stylesheet_link_tag "application", :media => "all" %>
>     16: 
>     17:     
>     18:     

下载您的代码能够正常运行，经过对比发现问题在于Gemfile.lock这个文件上，直接用您这里的Gemfile.lock 替换掉我本地生成的文件就可以正常运行。
下面是我的Gemfile.lock文件内容，请教老师我这种情况问题出在哪里？

> GEM
>  remote: http://rubygems.org/
>   specs:
>     actionmailer (4.2.0)
>       actionpack (= 4.2.0)
>       actionview (= 4.2.0)
>       activejob (= 4.2.0)
>       mail (~> 2.5, >= 2.5.4)
>       rails-dom-testing (~> 1.0, >= 1.0.5)
>     actionpack (4.2.0)
>       actionview (= 4.2.0)
>       activesupport (= 4.2.0)
>       rack (~> 1.6.0)
>       rack-test (~> 0.6.2)
>       rails-dom-testing (~> 1.0, >= 1.0.5)
>       rails-html-sanitizer (~> 1.0, >= 1.0.1)
>     actionview (4.2.0)
>       activesupport (= 4.2.0)
>       builder (~> 3.1)
>       erubis (~> 2.7.0)
>       rails-dom-testing (~> 1.0, >= 1.0.5)
>       rails-html-sanitizer (~> 1.0, >= 1.0.1)
>     activejob (4.2.0)
>       activesupport (= 4.2.0)
>       globalid (>= 0.3.0)
>     activemodel (4.2.0)
>       activesupport (= 4.2.0)
>       builder (~> 3.1)
>     activerecord (4.2.0)
>       activemodel (= 4.2.0)
>       activesupport (= 4.2.0)
>       arel (~> 6.0)
>     activesupport (4.2.0)
>       i18n (~> 0.7)
>       json (~> 1.7, >= 1.7.7)
>       minitest (~> 5.1)
>       thread_safe (~> 0.3, >= 0.3.4)
>       tzinfo (~> 1.1)
>     arel (6.0.3)
>     binding_of_caller (0.7.2)
>       debug_inspector (>= 0.0.1)
>     builder (3.2.2)
>     byebug (6.0.2)
>     coffee-rails (4.1.0)
>       coffee-script (>= 2.2.0)
>       railties (>= 4.0.0, < 5.0)
>     coffee-script (2.4.1)
>       coffee-script-source
>       execjs
>     coffee-script-source (1.9.1.1)
>     commonjs (0.2.7)
>     debug_inspector (0.0.2)
>     erubis (2.7.0)
>     execjs (2.6.0)
>     globalid (0.3.6)
>       activesupport (>= 4.1.0)
>     i18n (0.7.0)
>     jbuilder (2.3.1)
>       activesupport (>= 3.0.0, < 5)
>       multi_json (~> 1.2)
>     jquery-rails (4.0.5)
>       rails-dom-testing (~> 1.0)
>       railties (>= 4.2.0)
>       thor (>= 0.14, < 2.0)
>     json (1.8.3)
>     less (2.6.0)
>       commonjs (~> 0.2.7)
>     less-rails (2.6.0)
>       actionpack (>= 3.1)
>       less (~> 2.6.0)
>     libv8 (3.16.14.7)
>     loofah (2.0.3)
>       nokogiri (>= 1.5.9)
>     mail (2.6.3)
>       mime-types (>= 1.16, < 3)
>     mime-types (2.6.2)
>     mini_portile (0.6.2)
>     minitest (5.8.0)
>     multi_json (1.11.2)
>     nokogiri (1.6.6.2)
>       mini_portile (~> 0.6.0)
>     rack (1.6.4)
>     rack-test (0.6.3)
>       rack (>= 1.0)
>     rails (4.2.0)
>       actionmailer (= 4.2.0)
>       actionpack (= 4.2.0)
>       actionview (= 4.2.0)
>       activejob (= 4.2.0)
>       activemodel (= 4.2.0)
>       activerecord (= 4.2.0)
>       activesupport (= 4.2.0)
>       bundler (>= 1.3.0, < 2.0)
>       railties (= 4.2.0)
>       sprockets-rails
>     rails-deprecated_sanitizer (1.0.3)
>       activesupport (>= 4.2.0.alpha)
>     rails-dom-testing (1.0.7)
>       activesupport (>= 4.2.0.beta, < 5.0)
>       nokogiri (~> 1.6.0)
>       rails-deprecated_sanitizer (>= 1.0.1)
>     rails-html-sanitizer (1.0.2)
>       loofah (~> 2.0)
>     railties (4.2.0)
>       actionpack (= 4.2.0)
>       activesupport (= 4.2.0)
>       rake (>= 0.8.7)
>       thor (>= 0.18.1, < 2.0)
>     rake (10.4.2)
>     rdoc (4.2.0)
>     ref (1.0.5)
>     sass (3.4.18)
>     sass-rails (5.0.4)
>       railties (>= 4.0.0, < 5.0)
>       sass (~> 3.1)
>       sprockets (>= 2.8, < 4.0)
>       sprockets-rails (>= 2.0, < 4.0)
>       tilt (>= 1.1, < 3)
>     sdoc (0.4.1)
>       json (~> 1.7, >= 1.7.7)
>       rdoc (~> 4.0)
>     spring (1.4.0)
>     sprockets (3.3.4)
>       rack (~> 1.0)
>     sprockets-rails (2.3.3)
>       actionpack (>= 3.0)
>       activesupport (>= 3.0)
>       sprockets (>= 2.8, < 4.0)
>     sqlite3 (1.3.10)
>     therubyracer (0.12.1)
>       libv8 (~> 3.16.14.0)
>       ref
>     thor (0.19.1)
>     thread_safe (0.3.5)
>     tilt (2.0.1)
>     turbolinks (2.5.3)
>       coffee-rails
>     twitter-bootstrap-rails (3.2.0)
>       actionpack (~> 4.1)
>       execjs (~> 2.2)
>       rails (~> 4.1)
>       railties (~> 4.1)
>     tzinfo (1.2.2)
>       thread_safe (~> 0.1)
>     uglifier (2.7.2)
>       execjs (>= 0.3.0)
>       json (>= 1.8.0)
>     web-console (2.2.1)
>       activemodel (>= 4.0)
>       binding_of_caller (>= 0.7.2)
>       railties (>= 4.0)
>       sprockets-rails (>= 2.0, < 4.0)
> 
> PLATFORMS
>   ruby
> 
> DEPENDENCIES
>   byebug
>   coffee-rails (~> 4.1.0)
>   jbuilder (~> 2.0)
>   jquery-rails
>   less-rails
>   rails (= 4.2.0)
>   sass-rails (~> 5.0)
>   sdoc (~> 0.4.0)
>   spring
>   sqlite3
>   therubyracer
>   turbolinks
>   twitter-bootstrap-rails
>   uglifier (>= 1.3.0)
>   web-console (~> 2.0)
> 
> BUNDLED WITH
>    1.10.6

我的环境
OSX 10.10.5 YOSEMITE
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
Rails 4.2.0
Bundler version 1.10.6

**Comment by liwei78** [comment]
@jfcai 其实可以把 Gemfile.lock 删除掉的，下次 bundle install 的时候会再次生成。

另：我觉得问题是个别 gem 的版本问题，这是 rails 给新手造成的潜在大坑，一些看似很好的 gem，可能会引起各种问题，常见的是版本号的问题，所以我在 Gemfile.lock 里更直接换了版本号，但是自动生成的又会使用有问题的版本。

所以，如果现在没问题，就继续使用可用的，原理就是刚才解释的，不必一定要自动生成。

**Comment by jfcai** [comment]
感谢老师回复，确实是自动生成Gemfile.lock的问题。
