### ISSUE TITLE
不错的教程,但是在用rvm安装ruby2.2.1出现错误

### ISSUE THREAD

**Issue by LeoMustafa** [liwei78/rails-practice#17]
本人机器环境ubuntu14.04LTS,rvm1.2.6,安装ruby2.2.1过程中返回如下错误信息:
Error running '_rvm_make -j2',
showing last 15 lines of /home/frank/.rvm/log/1448881286_ruby-2.2.1/make.log
linking transcoder emoji_sjis_kddi.so
linking transcoder emoji_sjis_softbank.so
linking transcoder escape.so
linking transcoder gb18030.so
linking transcoder gbk.so
linking transcoder iso2022.so
linking transcoder japanese.so
linking transcoder japaneseeuc.so
linking transcoder japanese_sjis.so
linking transcoder korean.so
linking transcoder single_byte.so
linking transcoder utf8_mac.so
linking transcoder utf_16_32.so
make[1]:正在离开目录 `/home/frank/.rvm/src/ruby-2.2.1'
++ return 2
There has been an error while running make. Halting the installation.

make.log文件中错误信息如下:
/tmp/ccfwHw9f.s: Assembler messages:
/tmp/ccfwHw9f.s:14566: Error: unknown pseudo-op: .st2ing'
make[1]: **\* [enc/euc_tw.o] 错误 1
make[1]:正在离开目录/home/frank/.rvm/src/ruby-2.2.1'
make: **\* [enc] 错误 2
make: **\* 正在等待未完成的任务....
make[1]:正在离开目录 `/home/frank/.rvm/src/ruby-2.2.1'
++ return 2

网上查了一下相关信息,重试后问题还是出现,版主能帮忙看看是什么原因吗？

**Comment by liwei78** [comment]
谢谢。
再继续追查一下 log，应该是安装那个 lib 的时候缺少依赖，可能要 yum 单独安装一些 lib。

**Comment by LeoMustafa** [comment]
谢谢回复,问题已解决
