### ISSUE TITLE
非常赞的一个教程, 希望能更快点更新

### ISSUE THREAD

**Issue by windy** [liwei78/rails-practice#2]
我把它推荐给深圳的 Rubyer 了 :)

[Where to find good study resources about Ruby and Ruby on Rails in China](http://en.yafeilee.me/blogs/55328cc96c69347575020000)

**Comment by liwei78** [comment]
@windy 谢谢亚飞。最近忙，而且4、5章想写好也不容易，所以花了很多时间。我加油，把内容补充完。
